package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/gorilla/mux"
	"github.com/subosito/gotenv"
	"github.com/yanarowana123/onelab2_1/configs"
	_ "github.com/yanarowana123/onelab2_1/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/yanarowana123/onelab2_1/internal/repositories"
	"github.com/yanarowana123/onelab2_1/internal/services"
	"github.com/yanarowana123/onelab2_1/transport/http"
	"github.com/yanarowana123/onelab2_1/transport/http/handler"
	"log"
)

// main
// @securityDefinitions.apikey ServerKeyAuth
// @in header
// @name Secret-Key
func main() {
	gotenv.Load()
	if err := run(); err != nil {
		log.Fatal(err.Error())
	}
}

func run() error {
	config, err := configs.New()
	if err != nil {
		return err
	}

	repositoryManager := repositories.NewManager(*config)

	serviceManager := services.NewManager(*repositoryManager, *config)

	validate := validator.New()

	handlerManager := handler.NewManager(*serviceManager, validate)

	r := mux.NewRouter()
	router := http.InitRouter(r, *handlerManager)

	http.InitServer(*config, router)
	return nil
}
